# Generated by Django 3.2 on 2021-05-02 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EduLevel', models.CharField(max_length=100)),
                ('CourseName', models.CharField(max_length=100)),
                ('StartingYear', models.DateField()),
                ('IsAppearing', models.BooleanField()),
                ('PassOutYear', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.CharField(max_length=100)),
                ('Rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/blogimages')),
                ('address', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('qualifiction_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.qualifications')),
                ('skill_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.skills_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
