# Generated by Django 3.2 on 2021-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='qualifiction_user',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skill_user',
        ),
        migrations.AddField(
            model_name='resume',
            name='CourseName',
            field=models.CharField(default='MCA', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='EduLevel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='IsAppearing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='PassOutYear',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='StartingYear',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Qualifications',
        ),
        migrations.DeleteModel(
            name='Skills_data',
        ),
    ]
