# Generated by Django 3.2 on 2021-05-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table=None,
        ),
    ]
