# Generated by Django 3.2 on 2021-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
